name: Publish

on:
    push:
        branches:
            - master
jobs:
    master:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: publish:example
              uses: design4pro/actions-github-push-subdirectories@master
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
              with:
                  args: example design4pro
            - name: publish:themes
              uses: johno/actions-yarn@master
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  args: publish:ci
